---
- name: Install Homebrew packages
  when: ansible_os_family == "Darwin"
  homebrew: name={{ item }}
  with_items: "{{ brew_packages | default([]) }}"
  become: no
  tags:
    - pkg
    - brew

- name: Install APT packages
  when: ansible_os_family == "Debian"
  apt: name={{ item }}
  with_items: "{{ apt_packages | default([]) }}"
  become: yes
  tags:
    - pkg
    - apt

- name: Install NPM packages (for all users)
  npm: name={{ item }} global=yes
  with_items: "{{ npm_packages | default([]) }}"
  become: "{{ ansible_os_family != 'Darwin' }}"
  tags:
    - pkg
    - npm
