---
- name: Install Homebrew packages
  homebrew: name={{ item }}
  with_dict: "{{ brew_packages | default({}) }}"
  when:
    - ansible_os_family == "Darwin"
    - "'brew' in item.value"
  become: no
  tags:
    - pkg
    - brew

- name: Install APT packages
  apt: name={{ item.key }}
  with_dict: "{{ packages | default({}) }}"
  when:
    - ansible_os_family == "Debian"
    - "'apt' in item.value"
  become: yes
  tags:
    - pkg
    - apt

- name: Install FreeBSD packages
  pkgng: name={{ item.key }}
  with_dict: "{{ packages | default({}) }}"
  when:
    - ansible_os_family == "FreeBSD"
    - "'freebsd' in item.value"
  become: yes
  tags:
    - pkg
    - freebsd

- name: Install NPM packages (for all users)
  npm: name={{ item }} global=yes
  with_dict: "{{ packages | default([]) }}"
  when: "'npm' in item.value"
  become: "{{ ansible_os_family != 'Darwin' }}"
  tags:
    - pkg
    - npm
