---
- name: Install Homebrew packages
  homebrew: name={{ item.key }}
  with_dict: "{{ packages | default({}) }}"
  when:
    - ansible_os_family == "Darwin"
    - "'brew' in item.value"
  become: no
  tags:
    - pkg
    - brew

- name: Install Homebrew Cask packages
  homebrew_cask: name={{ item.key }}
  with_dict: "{{ packages | default({}) }}"
  when:
    - ansible_os_family == "Darwin"
    - "'brew_cask' in item.value"
  become: no
  tags:
    - pkg
    - brew
    - brew_cask

- name: Install APT packages
  apt: name={{ item.key }}
  with_dict: "{{ packages | default({}) }}"
  when:
    - ansible_os_family == "Debian"
    - "'apt' in item.value"
  become: yes
  tags:
    - pkg
    - apt

- name: Install FreeBSD packages
  pkgng: name={{ item.key }}
  with_dict: "{{ packages | default({}) }}"
  when:
    - ansible_os_family == "FreeBSD"
    - "'freebsd' in item.value"
  become: yes
  tags:
    - pkg
    - freebsd

- name: Install NPM packages (for all users)
  npm: name={{ item.key }} global=yes
  with_dict: "{{ packages | default([]) }}"
  when: "'npm' in item.value"
  become: "{{ ansible_os_family != 'Darwin' }}"
  tags:
    - pkg
    - npm
