- name: Install APT packages
  hosts: personal
  become: yes
  tasks:
    - apt: state=installed pkg={{item}} update_cache=yes
      with_items: "{{ lookup('file', 'packages/apt').split() }}"
      when: ansible_os_family == "Debian"

- name: Install YUM packages
  hosts: personal
  become: yes
  tasks:
    - yum: state=installed pkg={{item}} update_cache=yes
      with_items: "{{ lookup('file', 'packages/yum').split() }}"
      when: ansible_os_family == "RedHat"

- name: Install Homebrew packages
  hosts: personal
  become: no
  tasks:
    - homebrew: name={{item}} update_homebrew=yes
      with_items: "{{ lookup('file', 'packages/homebrew').split() }}"
      when: ansible_os_family == "Darwin"
    - homebrew_cask: name={{item}}
      with_items: "{{ lookup('file', 'packages/homebrew-cask').split() }}"
      when: ansible_os_family == "Darwin"

- name: Install NPM packages
  hosts: personal
  become: yes
  tasks:
    - npm: global=yes name={{item}}
      with_items: "{{ lookup('file', 'packages/npm').split() }}"
